
#This is yaml file to for package deployment
name: Custom Core publish
on:
  push:
    branches: ["main"]

permissions:
contents: read


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Install java 17 JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: GITHUB_USER_REF #env variable set in github account
          server-password: GITHUB_TOKEN_REF
          settings-path: ${{github.workspace}}

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_USER_REF: ${{ secrets.GIT_USERNAME_FOR_PUBLISH }}
          GITHUB_TOKEN_REF:  ${{ secrets.GIT_TOKEN_FOR_PUBLISH }}
